### ISSUE TITLE
Appreciation

### ISSUE THREAD

**Issue by Humorist2601** [vernette/Hyprsnap#1]
You have a really awesome config that is very distro agnostic and easy for a newbie like me to understand. Have all the essentials and nothing more imo. Other configs like end-4 and hyperdots and very confusing to follow. 

Kudos for making a beautiful and easy config.

If you can kindly help me for once script which is distro specific in your config "check_updates.sh". Can you guide me in how to convert it to check for updates on fedora and flatpak. I would really appreciate that.

Again. Thank you for making this config to help a newbie like me.

Edit: nvm, am switching to Arch to try it out. Will be using that instead of Fedora. Thanks again

**Comment by vernette** [comment]
Thank you, I really appreciate it!

Anyway, here's what I found for dnf and flatpak:

I haven't used Fedora before, but here's a similar command to get updates via dnf https://dnf.readthedocs.io/en/latest/command_ref.html#check-update-command

As for flatpak, I think you can use the following command:
```bash
flatpak remote-ls --updates
```
[Source](https://man7.org/linux/man-pages/man1/flatpak-remote-ls.1.html)
