### ISSUE TITLE
Rofi dependency problem with iwdrofimenu

### ISSUE THREAD

**Issue by baykalokandemir** [vernette/Hyprsnap#2]
Hi,

I've noticed you use a fork of rofi on your setup for some wayland feature support that I am too unfamiliar to comment on. This causes a dependency problem with pacman for iwdrofimenu, as it requires the regular rofi branch as a dependency. How were you able to get around this?

**Comment by baykalokandemir** [comment]
--nodeps flag resolves the issue

**Comment by vernette** [comment]
The reason I use the Wayland fork is very simple: the original rofi doesn't let you manipulate layers (apply blurs, animations, etc). In other words, its layers are not in the output of the `hyprctl layers` command.

Thanks for the `--nodeps` flag, I really couldn't install the package without it. I will update the README later!
